-- Instalacao completa para o SQL Editor do Supabase.
-- Pode ser executado novamente sem duplicar os dados de demonstracao.

create table if not exists public.categorias (
    id bigint generated by default as identity primary key,
    nome varchar(100) not null unique
);

create table if not exists public.usuarios (
    id bigint generated by default as identity primary key,
    nome varchar(100) not null,
    cnpj varchar(14) not null
);

create table if not exists public.produtos (
    id bigint generated by default as identity primary key,
    nome varchar(100) not null,
    valor numeric(12, 2) not null check (valor >= 0),
    descricao varchar(400),
    id_usuario bigint not null references public.usuarios(id),
    id_categoria bigint references public.categorias(id)
);

create table if not exists public.codigos_barra (
    id bigint generated by default as identity primary key,
    codigo varchar(128) not null unique,
    tipo_cod_barra varchar(50),
    id_produto bigint not null unique references public.produtos(id) on delete cascade
);

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on all tables in schema public to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

create or replace view public.vw_produtos_codigos
with (security_invoker = true)
as
select
    p.id as produto_id,
    p.nome as produto,
    p.descricao,
    p.valor,
    coalesce(c.nome, 'Sem categoria') as categoria,
    u.nome as usuario,
    cb.codigo,
    cb.tipo_cod_barra as tipo_codigo
from public.produtos p
join public.usuarios u on u.id = p.id_usuario
join public.codigos_barra cb on cb.id_produto = p.id
left join public.categorias c on c.id = p.id_categoria;

grant select on public.vw_produtos_codigos to anon, authenticated;

create or replace function public.calcular_valor_catalogo(p_id_usuario bigint)
returns numeric
language sql
stable
security invoker
set search_path = ''
as $$
    select coalesce(sum(p.valor), 0)
    from public.produtos p
    where p.id_usuario = p_id_usuario;
$$;

grant execute on function public.calcular_valor_catalogo(bigint) to anon, authenticated;

create or replace procedure public.sp_cadastrar_produto_com_codigo(
    in p_nome varchar,
    in p_descricao varchar,
    in p_valor numeric,
    in p_id_usuario bigint,
    in p_id_categoria bigint,
    in p_codigo varchar,
    in p_tipo_cod_barra varchar,
    inout p_produto_id bigint default null
)
language plpgsql
security invoker
set search_path = ''
as $$
begin
    insert into public.produtos (
        nome, descricao, valor, id_usuario, id_categoria
    ) values (
        p_nome, p_descricao, p_valor, p_id_usuario, p_id_categoria
    ) returning id into p_produto_id;

    insert into public.codigos_barra (
        codigo, tipo_cod_barra, id_produto
    ) values (
        p_codigo, p_tipo_cod_barra, p_produto_id
    );
end;
$$;

create or replace function public.cadastrar_produto_com_codigo(
    p_nome varchar,
    p_descricao varchar,
    p_valor numeric,
    p_id_usuario bigint,
    p_id_categoria bigint,
    p_codigo varchar,
    p_tipo_cod_barra varchar
)
returns bigint
language plpgsql
volatile
security invoker
set search_path = ''
as $$
declare
    v_produto_id bigint;
begin
    call public.sp_cadastrar_produto_com_codigo(
        p_nome,
        p_descricao,
        p_valor,
        p_id_usuario,
        p_id_categoria,
        p_codigo,
        p_tipo_cod_barra,
        v_produto_id
    );
    return v_produto_id;
end;
$$;

grant execute on procedure public.sp_cadastrar_produto_com_codigo(
    varchar, varchar, numeric, bigint, bigint, varchar, varchar, bigint
) to anon, authenticated;
grant execute on function public.cadastrar_produto_com_codigo(
    varchar, varchar, numeric, bigint, bigint, varchar, varchar
) to anon, authenticated;

insert into public.categorias (nome) values
    ('Alimentos'),
    ('Bebidas'),
    ('Limpeza'),
    ('Categoria sem produto')
on conflict (nome) do nothing;

insert into public.usuarios (nome, cnpj)
select 'Mercado Exemplo', '12345678000190'
where not exists (
    select 1 from public.usuarios where cnpj = '12345678000190'
);

insert into public.produtos (nome, valor, descricao, id_usuario, id_categoria)
select
    'Cafe 500g', 18.90, 'Cafe torrado e moido', u.id, c.id
from public.usuarios u
join public.categorias c on c.nome = 'Alimentos'
where u.cnpj = '12345678000190'
  and not exists (select 1 from public.produtos where nome = 'Cafe 500g');

insert into public.codigos_barra (codigo, tipo_cod_barra, id_produto)
select '7891234567890', 'EAN-13', p.id
from public.produtos p
where p.nome = 'Cafe 500g'
on conflict (codigo) do nothing;

