create table if not exists public.categorias (
    id bigint generated by default as identity primary key,
    nome varchar(100) not null unique
);

create table if not exists public.usuarios (
    id bigint generated by default as identity primary key,
    nome varchar(100) not null,
    cnpj varchar(14) not null
);

create table if not exists public.produtos (
    id bigint generated by default as identity primary key,
    nome varchar(100) not null,
    valor numeric(12, 2) not null check (valor >= 0),
    descricao varchar(400),
    id_usuario bigint not null references public.usuarios(id),
    id_categoria bigint references public.categorias(id)
);

create table if not exists public.codigos_barra (
    id bigint generated by default as identity primary key,
    codigo varchar(128) not null unique,
    tipo_cod_barra varchar(50),
    id_produto bigint not null unique references public.produtos(id) on delete cascade
);

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on all tables in schema public to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

-- Projeto academico sem login: RLS permanece desativada para a chave publica.
-- Em producao, habilite RLS e crie politicas vinculadas ao auth.uid().

